FROM adoptopenjdk/openjdk11:latest
ADD target/geotracking-synchronous-microservice-*.jar geotracking-synchronous-microservice.jar
ENTRYPOINT ["java", "-jar", "geotracking-synchronous-microservice.jar"]
