FROM adoptopenjdk/openjdk11:latest
ADD target/geotracking-reactive-functional-microservice-*.jar geotracking-reactive-functional-microservice.jar
ENTRYPOINT ["java", "-jar", "geotracking-reactive-functional-microservice.jar"]
