spring:
  config:
    activate:
      on-profile: "docker"

  data:
    mongodb:
      uri: mongodb://mongodb:27017/demo_webflux

logging:
  level:
    #root: DEBUG
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG     #DEBUG #ERROR
    org.springframework.data.mongodb.repository.query: DEBUG       #DEBUG #ERROR


