FROM adoptopenjdk/openjdk11:latest
ADD target/geotracking-reactive-annotation-microservice-*.jar geotracking-reactive-annotation-microservice.jar
ENTRYPOINT ["java", "-jar", "geotracking-reactive-annotation-microservice.jar"]
