spring:
  config:
    activate:
      on-profile: "local"

  data:
    mongodb:
      uri: mongodb://localhost:27017/demo_webflux?retryWrites=true&w=majority&maxPoolSize=100&maxIdleTimeMS=120000
#      maxConnectionIdleTime: 15000
#      connectionsPerHost: 40
#      minConnectionsPerHost: 1
#      socketTimeout: 60000

logging:
  level:
    #root: DEBUG
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG     #DEBUG #ERROR
    org.springframework.data.mongodb.repository.query: DEBUG       #DEBUG #ERROR


